services:
  bot:
    build: ./
    container_name: telegram_task_bot
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/telegram_bot
    depends_on:
      - db
    volumes:
      - ./:/app
    networks:
      - botnet

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - botnet

volumes:
  postgres_data:

networks:
  botnet:
    driver: bridge
